### ISSUE TITLE
Documentar os métodos da classe Pessoa

### ISSUE THREAD

**Issue by bigois** [guilhermebigois/gorilla-tank#6]
Utilizar a extensão [ProtheusDoc for VsCode (AdvPL)](https://marketplace.visualstudio.com/items?itemName=AlencarGabriel.protheusdoc-vscode) como base para documentação da classe Pessoa.

**Comment by guilhermebigois** [comment]
ℹ️ Solicitação resolvida no commit [618b369ed13cc099ac2b69391916036789db4c80](https://github.com/guilhermebigois/gorilla-tank/commit/618b369ed13cc099ac2b69391916036789db4c80).

**Comment by bigois** [comment]
ℹ️ Solicitação resolvida no commit [618b369ed13cc099ac2b69391916036789db4c80](https://github.com/guilhermebigois/gorilla-tank/commit/618b369ed13cc099ac2b69391916036789db4c80).
